"""add account name and decimal balance

Revision ID: 898ec1394bb6
Revises: 752538f51fb8
Create Date: 2025-10-09 17:19:28.940208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '898ec1394bb6'
down_revision: Union[str, Sequence[str], None] = '752538f51fb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accounts",
        sa.Column(
            "account_name",
            sa.String(),
            nullable=False,
            server_default=sa.text("'Unnamed Account'"),
        ),
    )
    op.alter_column('accounts', 'balance',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'balance',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('accounts', 'account_name')
    # ### end Alembic commands ###
